codestates-seb/seb44_main_014

- client/.gitignore
- client/README.md
- client/src/components/BoardList.tsx
- client/src/index.css
- client/src/pages/Board.tsx
- client/src/pages/PageRouter.tsx
- client/src/styles/GlobalStyle.tsx
- client/vite.config.ts
- Board mobile 사이즈 작업
- 글로벌 스타일 수정
> feat: Board mobile

- client/src/components/layout/Header.tsx
768px;
Container> height 50px;
Left, Right > width: 30px;
Title > font-size: 24px;
RightContents > display: none;
HamburgerIcon > display: block;
375px;
Positioner > margin 30px;
> feat: 헤더 제작

- client/src/components/BoardList.tsx
- client/src/pages/Board.tsx
- 반응형
- typescript 오류 수정
- axios 작성 후 주석처리
> feat: board page

- server/bf/build.gradle
- server/bf/src/main/java/com/bobfriends/bf/config/QuerydslConfiguration.java
- server/bf/src/main/java/com/bobfriends/bf/post/controller/PostController.java
- server/bf/src/main/java/com/bobfriends/bf/post/dto/PostDto.java
- server/bf/src/main/java/com/bobfriends/bf/post/entity/Post.java
- server/bf/src/main/java/com/bobfriends/bf/post/mapper/PostMapper.java
- server/bf/src/main/java/com/bobfriends/bf/post/repository/PostRepository.java
- server/bf/src/main/java/com/bobfriends/bf/post/repository/PostRepositoryCustom.java
- server/bf/src/main/java/com/bobfriends/bf/post/repository/PostRepositoryImpl.java
- server/bf/src/main/java/com/bobfriends/bf/post/service/PostService.java
- server/bf/src/main/java/com/bobfriends/bf/utils/PageRequest.java
- server/bf/src/main/resources/db/h2/data.sql
[영상 코드 리뷰 완료 했습니다]
1. 위치 필드 삭제 (Post)
2. Querydsl을 사용한 질문 검색 구현
> feat: 질문 검색 구현

- server/bf/build.gradle
- server/bf/src/main/java/com/bobfriends/bf/comment/dto/CommentDto.java
- server/bf/src/main/java/com/bobfriends/bf/comment/mapper/CommentMapper.java
- server/bf/src/main/java/com/bobfriends/bf/post/dto/PostDto.java
- server/bf/src/main/java/com/bobfriends/bf/post/mapper/PostMapper.java
- server/bf/src/test/java/com/bobfriends/bf/util/ApiDocumentUtils.java
[영상 코드 리뷰 완]
1. build.gradle 파일 수정
2. ApiDocumentUtils 추가
> Feat: ApiDocumentUtils 추가

- client/src/components/fetch/LoginPost.tsx
- client/src/components/fetch/SignUpPost.tsx
- client/src/pages/Login.tsx
- client/src/pages/SignUp.tsx
로그인, 회원가입 컴포넌트 및 로그인, 회원가입에서 사용되는 서버 요청 컴포넌트 입니다.
JS는 완성한 상태입니다. TS로 리펙토링 해서 pr날리기전 백업용도로 PR보냅니다.
> Feat: 로그인, 회원가입 컴포넌트 js 완성

- server/bf/build.gradle
- server/bf/src/docs/asciidoc/index.adoc
- server/bf/src/main/java/com/bobfriends/bf/post/dto/PostDto.java
- server/bf/src/main/java/com/bobfriends/bf/post/entity/Post.java
- server/bf/src/main/java/com/bobfriends/bf/post/mapper/PostMapper.java
- server/bf/src/main/java/com/bobfriends/bf/post/service/PostService.java
- server/bf/src/main/java/com/bobfriends/bf/upload/config/AmazonS3Config.java
- server/bf/src/main/java/com/bobfriends/bf/upload/service/S3Uploader.java
- server/bf/src/main/resources/application.yml
- server/bf/src/test/java/com/bobfriends/bf/helper/StubData.java
- server/bf/src/test/java/com/bobfriends/bf/home/controller/HomeControllerTest.java
- server/bf/src/test/java/com/bobfriends/bf/post/controller/PostControllerTest.java
[영상 코드 리뷰 완료 했습니다]
1. Controller 테스트 코드 
2. S3 관련 코드
> Feat/be/post 

- client/src/pages/UserInfo.tsx
> Feat: UserInfo UI작성완료

- client/src/components/UI/Button.tsx
- client/src/pages/UserInfo.tsx
UserInfo data 전송 기능 추가했습니다.
data 형식에 수정이 필요합니다.
image이외의 정보를 blob으로 data 변수에 담아서 추가하게 되면 body에 key로 image, data가 들어가게 되어서 api 명세서와 데이터 형식이 다를 것.
어떻게 해결할지 고민중입니다.
> Feat: UserInfo data 전송기능 추가

- server/bf/src/main/java/com/bobfriends/bf/comment/dto/CommentDto.java
- server/bf/src/main/java/com/bobfriends/bf/comment/mapper/CommentMapper.java
- server/bf/src/main/java/com/bobfriends/bf/mate/dto/MateDto.java
- server/bf/src/main/java/com/bobfriends/bf/mate/mapper/MateMapper.java
- server/bf/src/main/java/com/bobfriends/bf/mate/mapper/MateMemberMapper.java
- server/bf/src/main/java/com/bobfriends/bf/member/controller/MemberController.java
- server/bf/src/main/java/com/bobfriends/bf/member/dto/MemberDto.java
- server/bf/src/main/java/com/bobfriends/bf/member/dto/MemberTagDto.java
- server/bf/src/main/java/com/bobfriends/bf/member/entity/Member.java
- server/bf/src/main/java/com/bobfriends/bf/member/mapper/MemberMapper.java
- server/bf/src/main/java/com/bobfriends/bf/member/service/MemberService.java
- server/bf/src/main/java/com/bobfriends/bf/member/service/MemberTagService.java
- server/bf/src/main/java/com/bobfriends/bf/post/dto/PostDto.java
- server/bf/src/main/java/com/bobfriends/bf/post/mapper/PostMapper.java
> Fix: 회원 정보 수정, 최초 회원 정보 등록

- server/bf/src/main/java/com/bobfriends/bf/auth/filter/JwtAuthenticationFilter.java
- server/bf/src/main/java/com/bobfriends/bf/auth/handler/MemberAuthenticationSuccessHandler.java
- server/bf/src/main/java/com/bobfriends/bf/comment/repository/CommentRepository.java
- server/bf/src/main/java/com/bobfriends/bf/member/controller/MemberController.java
- server/bf/src/main/java/com/bobfriends/bf/member/dto/MemberDto.java
- server/bf/src/main/java/com/bobfriends/bf/member/entity/Member.java
- server/bf/src/main/java/com/bobfriends/bf/member/mapper/MemberMapper.java
- server/bf/src/main/java/com/bobfriends/bf/member/service/MemberService.java
- server/bf/src/main/java/com/bobfriends/bf/post/repository/PostRepository.java
> Fix: user 마저 수정, jwt 로그인 reponse 추가

- client/src/pages/MoreInfoComments.tsx
- client/src/pages/MoreInfoWritings.tsx
- client/src/pages/PageRouter.tsx
> design: MoreInfo(글,댓글) 페이지 레이아웃

- client/src/pages/Mypage.tsx
> design: 마이페이지 레이아웃

- server/bf/build.gradle
- server/bf/src/main/java/com/bobfriends/bf/auth/config/SecurityConfiguration.java
- server/bf/src/main/java/com/bobfriends/bf/auth/controller/AuthController.java
- server/bf/src/main/java/com/bobfriends/bf/auth/filter/JwtAuthenticationFilter.java
- server/bf/src/main/java/com/bobfriends/bf/auth/filter/JwtVerificationFilter.java
- server/bf/src/main/java/com/bobfriends/bf/auth/handler/MemberAccessDeniedHandler.java
- server/bf/src/main/java/com/bobfriends/bf/auth/handler/MemberAuthenticationEntryPoint.java
- server/bf/src/main/java/com/bobfriends/bf/auth/handler/MemberAuthenticationFailureHandler.java
- server/bf/src/main/java/com/bobfriends/bf/auth/handler/OAuth2MemberSuccessHandler.java
- server/bf/src/main/java/com/bobfriends/bf/auth/jwt/JwtTokenizer.java
- server/bf/src/main/java/com/bobfriends/bf/auth/service/AuthService.java
- server/bf/src/main/java/com/bobfriends/bf/auth/utils/CustomAuthorityUtils.java
> Fix: Jwt 권한 설정

- server/bf/src/main/java/com/bobfriends/bf/auth/config/SecurityConfiguration.java
- server/bf/src/main/java/com/bobfriends/bf/auth/controller/AuthController.java
- server/bf/src/main/java/com/bobfriends/bf/auth/entity/RefreshToken.java
- server/bf/src/main/java/com/bobfriends/bf/auth/filter/JwtAuthenticationFilter.java
- server/bf/src/main/java/com/bobfriends/bf/auth/handler/OAuth2MemberSuccessHandler.java
- server/bf/src/main/java/com/bobfriends/bf/auth/jwt/JwtTokenizer.java
- server/bf/src/main/java/com/bobfriends/bf/auth/repository/RefreshTokenRepository.java
- server/bf/src/main/java/com/bobfriends/bf/auth/service/AuthService.java
- server/bf/src/main/java/com/bobfriends/bf/exception/ExceptionCode.java
- server/bf/src/main/java/com/bobfriends/bf/member/entity/Member.java
- server/bf/src/main/java/com/bobfriends/bf/member/entity/MemberStarRate.java
- server/bf/src/main/java/com/bobfriends/bf/member/service/MemberStarRateService.java
> Feat: jwt 로그인, Access Token 재발급, AvgStarRate 평균 계산 적용

- server/bf/src/main/java/com/bobfriends/bf/auth/controller/AuthController.java
- server/bf/src/main/java/com/bobfriends/bf/auth/handler/MemberAuthenticationFailureHandler.java
- server/bf/src/main/java/com/bobfriends/bf/auth/service/AuthService.java
- server/bf/src/main/resources/application-server.yml
> Feat: 로그아웃 구현, 에러 메시지 구현

- server/bf/build.gradle
- server/bf/src/main/java/com/bobfriends/bf/advice/GlobalExceptionAdvice.java
- server/bf/src/main/java/com/bobfriends/bf/audit/Auditable.java
- server/bf/src/main/java/com/bobfriends/bf/comment/controller/CommentController.java
- server/bf/src/main/java/com/bobfriends/bf/exception/ExceptionCode.java
- server/bf/src/main/java/com/bobfriends/bf/mate/service/MateMemberService.java
- server/bf/src/main/java/com/bobfriends/bf/post/service/PostService.java
- server/bf/src/main/java/com/bobfriends/bf/upload/config/AmazonS3Config.java
- server/bf/src/main/java/com/bobfriends/bf/upload/service/S3Uploader.java
- server/bf/src/main/java/com/bobfriends/bf/utils/PageRequest.java
> Feat: mate 등록 성별 에러 구현

- server/bf/src/main/java/com/bobfriends/bf/auth/config/SecurityConfiguration.java
> Fix: Refresh 이름 변경

- client/src/pages/Mypage.tsx
> feat: 마이페이지 기능 구현

- client/src/pages/Location.tsx
- client/src/pages/Login.tsx
- client/src/util/api/postLogin.tsx
> Fix: Login 오류시 에러메시지 출력 안되는 에러 핸들링

- client/src/components/Logout/Logout.tsx
- client/src/components/layout/Header.tsx
- client/src/pages/Login.tsx
Design: Oauth 로그인 버튼 삭제 - login page
> Fix: UserInfo에서 다른 페이지로 넘어가는 경로 차단-header수정

- server/bf/src/main/java/com/bobfriends/bf/mate/dto/MateMemberDto.java
- server/bf/src/main/java/com/bobfriends/bf/mate/mapper/MateMemberMapper.java
> fix : mate response 추가

- server/bf/src/main/java/com/bobfriends/bf/comment/dto/CommentDto.java
- server/bf/src/main/java/com/bobfriends/bf/comment/mapper/CommentMapper.java
- server/bf/src/main/java/com/bobfriends/bf/mate/dto/MateMemberDto.java
- server/bf/src/main/java/com/bobfriends/bf/member/controller/MemberController.java
- server/bf/src/main/java/com/bobfriends/bf/member/dto/MemberDto.java
- server/bf/src/main/java/com/bobfriends/bf/member/repository/MemberRepository.java
- server/bf/src/main/java/com/bobfriends/bf/member/service/MemberService.java
- server/bf/src/main/java/com/bobfriends/bf/post/repository/PostRepositoryImpl.java
- server/bf/src/main/java/com/bobfriends/bf/post/service/PostService.java
> Feat: 이름 중복 확인

- server/bf/src/main/java/com/bobfriends/bf/location/service/LocationService.java
- server/bf/src/main/java/com/bobfriends/bf/post/controller/PostController.java
- server/bf/src/main/java/com/bobfriends/bf/post/repository/PostRepository.java
- server/bf/src/main/java/com/bobfriends/bf/post/repository/PostRepositoryCustom.java
- server/bf/src/main/java/com/bobfriends/bf/post/repository/PostRepositoryImpl.java
- server/bf/src/main/java/com/bobfriends/bf/post/service/PostService.java
> Fix: 게시글 검색 recruit 추가

- client/src/pages/EditUserInfo.tsx
editUserInfo 저장 시, mypage에 데이터 싱크 안 맞는 오류 해결
> fix: data sync error
